### ISSUE TITLE
Does not build on windows

### ISSUE THREAD

**Issue by hitesh97** [workco/react-redux-webpack2-boilerplate#15]
Hi There, I really liked your blog and was trying to clone this repository to start my development project based on this template.
I cloned repository and tried to build using 'npm run start' as per your readme.md file, however it gives me following error.
I have latest verison of NodeJs & npm.

Can you please let me know what could be the issue?

following is the content of the 'npm-debug.log' file
---------------------------------------------------------------------------------------------------------

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-redux-webpack2-boilerplate@0.1.4~prestart: react-redux-webpack2-boilerplate@0.1.4
6 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~prestart: no script for prestart, continuing
7 info lifecycle react-redux-webpack2-boilerplate@0.1.4~start: react-redux-webpack2-boilerplate@0.1.4
8 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Workspace\Source\react-redux-webpack2-boilerplate\node_modules\.bin;C:\windows\system32\WindowsPowerShell\v1.0\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\khatrih\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Nuget;C:\Program Files\Amazon\AWSCLI\;;C:\Program Files\RabbitMQ Server\rabbitmq_server-3.6.6\sbin;C:\Program Files\dotnet\;C:\Program Files (x86)\scala\bin;C:\Program Files\apache-maven\bin;C:\Program Files (x86)\sbt\bin;C:\jdk1.8.0_121\bin;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Ruby23-x64\bin;C:\Users\khatrih\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: CWD: C:\Workspace\Source\react-redux-webpack2-boilerplate
11 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dashboard -t \'React-Redux Boilerplate\' -- webpack-dev-server --colors --no-info' ]
12 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Returned: code: 1  signal: null
13 info lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Failed to exec start script
14 verbose stack Error: react-redux-webpack2-boilerplate@0.1.4 start: `webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-redux-webpack2-boilerplate@0.1.4
16 verbose cwd C:\Workspace\Source\react-redux-webpack2-boilerplate
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-redux-webpack2-boilerplate@0.1.4 start: `webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info`
22 error Exit status 1
23 error Failed at the react-redux-webpack2-boilerplate@0.1.4 start script 'webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-webpack2-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-webpack2-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-webpack2-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Stanko** [comment]
Hello, this seems like you haven't run `npm install` prior running `npm start`.

**Comment by mantesat** [comment]
Hi,

I also just tried to checkout and install/run it on both Windows 7 and 10, it fails to run.

npm debug log follows:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-redux-webpack2-boilerplate@0.1.4~prestart: react-redux-webpack2-boilerplate@0.1.4
6 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~prestart: no script for prestart, continuing
7 info lifecycle react-redux-webpack2-boilerplate@0.1.4~start: react-redux-webpack2-boilerplate@0.1.4
8 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;c:\Projects\Javascript\npm\react-redux-webpack2-boilerplate\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Users\mantesat\AppData\Local\Microsoft\WindowsApps;C:\Users\mantesat\AppData\Roaming\npm
10 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: CWD: c:\Projects\Javascript\npm\react-redux-webpack2-boilerplate
11 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dashboard -t \'React-Redux Boilerplate\' -- webpack-dev-server --colors --no-info' ]
12 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Returned: code: 1  signal: null
13 info lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Failed to exec start script
14 verbose stack Error: react-redux-webpack2-boilerplate@0.1.4 start: `webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-redux-webpack2-boilerplate@0.1.4
16 verbose cwd c:\Projects\Javascript\npm\react-redux-webpack2-boilerplate
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-redux-webpack2-boilerplate@0.1.4 start: `webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info`
22 error Exit status 1
23 error Failed at the react-redux-webpack2-boilerplate@0.1.4 start script 'webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-webpack2-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-webpack2-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-webpack2-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dhilt** [comment]
I can confirm the issue (Win 10), here is my `npm start` log (of course I run it after `npm install`).
```
$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-redux-webpack2-boilerplate@0.1.4~prestart: react-redux-webpack2-boilerplate@0.1.4
6 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~prestart: no script for prestart, continuing
7 info lifecycle react-redux-webpack2-boilerplate@0.1.4~start: react-redux-webpack2-boilerplate@0.1.4
8 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: PATH: C:\Users\dhilt\AppData\Roaming\nvm\v6.10.0\node_modules\npm\bin\node-gyp-bin;D:\Denis\work\mkdev\_dhilt\react-redux-webpack2-boilerplate\node_modules\.bin;C:\Users\dhilt\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\dhilt\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Java\jre1.8.0_111\bin;C:\Users\dhilt\AppData\Local\Android\sdk\platform-tools;C:\Users\dhilt\AppData\Local\Android\sdk\tools;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0;C:\Program Files (x86)\Skype\Phone;C:\Users\dhilt\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Heroku\bin;C:\Vagrant\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Program Files\Java\jre1.8.0\bin;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft Emulator Manager\1.0;C:\Users\dhilt\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\SQLite3;C:\Program Files\PostgreSQL\9.5\bin;C:\Users\dhilt\AppData\Local\atom\bin;C:\Users\dhilt\AppData\Roaming\npm;C:\Users\dhilt\AppData\Local\Microsoft\WindowsApps;D:\Heroku\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: CWD: D:\Denis\work\mkdev\_dhilt\react-redux-webpack2-boilerplate
11 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dashboard -t \'React-Redux Boilerplate\' -- webpack-dev-server --colors --no-info' ]
12 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Returned: code: 1  signal: null
13 info lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Failed to exec start script
14 verbose stack Error: react-redux-webpack2-boilerplate@0.1.4 start: `webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\dhilt\AppData\Roaming\nvm\v6.10.0\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\dhilt\AppData\Roaming\nvm\v6.10.0\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-redux-webpack2-boilerplate@0.1.4
16 verbose cwd D:\Denis\work\mkdev\_dhilt\react-redux-webpack2-boilerplate
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-redux-webpack2-boilerplate@0.1.4 start: `webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info`
22 error Exit status 1
23 error Failed at the react-redux-webpack2-boilerplate@0.1.4 start script 'webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-webpack2-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-webpack2-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-webpack2-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Stanko** [comment]
Hmmmm I have no access to windows machine, could someone run `webpack-dev-server` and check if it works that way? 

You might need to install webpack `npm i -g webpack-dev-server` or run it from local packages `./node_modules/webpack-dev-server/bin/webpack-dev-server.js` (not sure how the second one works on windows).

**Comment by dhilt** [comment]
@Stanko Looks like it works, I'm able to open the proj on http://localhost:3000/ after `webpack-dev-server`.

```
$  webpack-dev-server
Project is running at http://0.0.0.0:3000/
webpack output is served from /
Content not from webpack is served from D:\Denis\work\mkdev\_dhilt\react-redux-webpack2-boilerplate\source
404s will fallback to /index.html
webpack: wait until bundle finished: /
Time: 22689ms
                                            Asset       Size  Chunks                    Chunk Names
assets/book1-dbff2b40ab3fe637247770798269fd9a.jpg    65.5 kB          [emitted] 
assets/book2-1240e90615f6ac37ab2e647e25b64c20.jpg    60.2 kB          [emitted] 
                      app-efb9d7746cd1823d77f3.js    67.5 kB       0  [emitted]         js
                   vendor-efb9d7746cd1823d77f3.js    2.09 MB       1  [emitted]  [big]  vendor
                  app-efb9d7746cd1823d77f3.js.map      32 kB       0  [emitted]         js
               vendor-efb9d7746cd1823d77f3.js.map     2.5 MB       1  [emitted]         vendor
                                       index.html  450 bytes          [emitted] 
webpack: Compiled successfully.
```

**Comment by Stanko** [comment]
@dhilt great, that isolates the problem. [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) seems to fail on windows. 

You can use this as a workaround, until I solve it. Also I'm open for suggestions, as I don't have windows machine around.

**Comment by dhilt** [comment]
@Stanko Thanks! You may ask me to run whatever on Win machine at any time. Maybe some package version should be downgraded and fixed...

**Comment by staranco** [comment]
Hi there! webpack-dev-server solution didn't work for me :( I'm running on Windows 10. This is my npm-debug-log:

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-redux-webpack2-boilerplate@0.1.4~prestart: react-redux-webpack2-boilerplate@0.1.4
6 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~prestart: no script for prestart, continuing
7 info lifecycle react-redux-webpack2-boilerplate@0.1.4~start: react-redux-webpack2-boilerplate@0.1.4
8 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\staranco\WebstormProjects\react-scoreboard\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\staranco\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Perforce;C:\Program Files\Perforce\DVCS\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Git\cmd;C:\Program Files\nodejs\;C:\Users\staranco\AppData\Local\Microsoft\WindowsApps;C:\Users\staranco\AppData\Roaming\npm
10 verbose lifecycle react-redux-webpack2-boilerplate@0.1.4~start: CWD: C:\Users\staranco\WebstormProjects\react-scoreboard
11 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dashboard -t \'React-Redux Boilerplate\' -- webpack-dev-server --colors --no-info' ]
12 silly lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Returned: code: 1  signal: null
13 info lifecycle react-redux-webpack2-boilerplate@0.1.4~start: Failed to exec start script
14 verbose stack Error: react-redux-webpack2-boilerplate@0.1.4 start: `webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-redux-webpack2-boilerplate@0.1.4
16 verbose cwd C:\Users\staranco\WebstormProjects\react-scoreboard
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-redux-webpack2-boilerplate@0.1.4 start: `webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info`
22 error Exit status 1
23 error Failed at the react-redux-webpack2-boilerplate@0.1.4 start script 'webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-webpack2-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-webpack2-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-webpack2-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by dhilt** [comment]
@staranco `verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]` in your log tells us that you just called `npm start`. Run `webpack-dev-server` and show us the console output.

**Comment by staranco** [comment]
Youre right! sorry! Heres the log when I run webpack-dev-server

C:\Users\staranco\WebstormProjects\react-redux-webpack2-boilerplate>npm i -g webpack-dev-server
C:\Users\staranco\AppData\Roaming\npm\webpack-dev-server -> C:\Users\staranco\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js
C:\Users\staranco\AppData\Roaming\npm
+-- UNMET PEER DEPENDENCY webpack@^2.2.0
`-- webpack-dev-server@2.4.5
  `-- UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN webpack-dev-server@2.4.5 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN webpack-dev-middleware@1.10.2 requires a peer of webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0 but none was installed.

**Comment by dhilt** [comment]
@staranco Looks likes you aren't able to install webpack-dev-server due to dependency on webpack 2. Do you have webpack 2 installed globally? Also you can try to run `webpack-dev-server` without installing it globally.

**Comment by staranco** [comment]
Sure @dhilt ! Ive webpack 2 installed globally, webpack -v logs 2.5.1

**Comment by staranco** [comment]
Just in case you want to check my procedure out... I leave it here. Can't keep trying in a few hours but I'll check it again later
[log.txt](https://github.com/workco/react-redux-webpack2-boilerplate/files/993282/log.txt)

**Comment by dhilt** [comment]
@Stanko I still don't see simple `webpack-dev-server` run try in your log...

**Comment by staranco** [comment]
Great!, just had to run webpack-dev-server and it worked perfectly. Thanks a lot guys!

**Comment by Stanko** [comment]
Sorry peeps, I'm out of town, we'll back next week and try to solve it.

**Comment by Stanko** [comment]
Hey everyone, `npm start` won't use webpack dashboard by default (as it still has issues on windows). [Check the updated docs](https://github.com/workco/react-redux-webpack2-boilerplate#running-in-dev-mode).

To run it with dashboard use `npm run dev`.

If you have existing project replace `start` task with this one:

```
"start": "webpack-dev-server --colors",
"dev": "webpack-dashboard -t 'React-Redux Boilerplate' -- webpack-dev-server --colors --no-info",
```

Hope that helps!
