### ISSUE TITLE
Production Build: Heroku

### ISSUE THREAD

**Issue by jgeraghty** [workco/react-redux-webpack2-boilerplate#17]
Have you launched this into production? Even more specifically with heroku? I am fairly new to react/webpack and found this project so i am just trying to see if i can get something live but when I push to heroku it doesn't build and doesn't give me much help except pointing at the packages start script line: "webpack-dashboard -t 'Police Stream' -- webpack-dev-server --colors --no-info".

**Comment by Stanko** [comment]
Hello, I see you closed it already, but yeah, I did run this on production level projects 3 or 4 so far. No experience with heroku though.
